version: '3.4'

networks:
  default:

services:
  nginx:
    image: nginx:1.17.9-alpine
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${PWD}/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/data/nginx/ssl:/etc/ssl:ro
    networks:
      - default
    depends_on:
      - api
  api:
    build:
      context: ${SOURCES_PATH}
      dockerfile: modules/api/Dockerfile
    volumes:
      - "${PWD}/config/explorer-api.conf:/etc/explorer-api.conf"
    command: /etc/explorer-api.conf
    networks:
      - default
    logging:
      options:
        max-size: "10m"
        max-file: "10"